#import "./timeline.typ": page-margin, page-kicker, bleed-x, paper, ink

#set page(
  paper: "us-letter",
  margin: (x: page-margin.x, y: page-margin.y),
  fill: paper,
)

#set text(
  font: "Avenir Next",
  size: 8.7pt,
  fill: ink,
)

#set par(
  leading: 0.58em,
)

#page-kicker("THE APP")

#set par(spacing: 12pt, leading: 10pt)
#set text(size: 10pt)

= Freeform Content publishing VIA Web-Technologies

A core axiom: content authoring and content presentation should be different mediums. Each best suited for their respective mediums. So that the needs of one does not interfere with the requirements of the other.

#bleed-x[
  #image("../assets/SubscriptScreenshot.png")
]

#bleed-x[
  #grid(
    columns: (1fr, 130pt, 1fr),
    [
      #align(right)[
        #image("../assets/old-webpage-screenshot.png", width: 90%)
      ]
    ],
    [
      #set par(justify: true)
      #align(center + horizon)[
        #text(
          size: 10pt,
          fill: rgb("#313030"),
        )[
          Screenshots of my actual chemistry notes. \
          Later added dark mode support among other improvements but unfortunately I lost the original model file.
        ]
      ]
    ],
    [
      #align(left)[
        #image("../assets/old-webpage-screenshot-alt.png", width: 90%)
      ]
    ],
  )
]

#grid(
  columns: (1fr, 1fr),
  column-gutter: 20pt,
  [
    == Editing Layer
    
    - Native platform specific support.
    - UI optimized for content authoring; support fast and efficient workflows desired by power users.
  ],
  [
    == Presentation Layer

    - Optimized for reading, content consumption, accessability.
    - Self contained dependency free webpages.
    - Hyperlinked document trees; autogenerated table of contents down to individual sections
    - Scalable vector graphics on the web
    - Cross platform
  ],
)

